package br.com.pedrocamargo.vrvendas.view;

import br.com.pedrocamargo.vrvendas.controller.ClienteController;
import br.com.pedrocamargo.vrvendas.controller.ProdutoController;
import br.com.pedrocamargo.vrvendas.controller.VendaController;
import br.com.pedrocamargo.vrvendas.model.ClienteModel;
import br.com.pedrocamargo.vrvendas.model.ProdutoModel;
import java.awt.BorderLayout;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.ExibirJanelaUtil;
import util.GerarTabelaUtil;


public class NovaVendaView extends javax.swing.JInternalFrame {
    
    ClienteController clienteController;
    ProdutoController produtoController;
    VendaController vendaController;
    String[] nomeColunas = {"ID", "Descricao", "Quantidade", "Unidade", "Total", "Estoque Atual"};
    GerarTabelaUtil gerarTabela = new GerarTabelaUtil(nomeColunas,false);
    
   public NovaVendaView() {
       this.clienteController = new ClienteController();
       this.produtoController = new ProdutoController();
       this.vendaController = new VendaController();
       vendaController.criarNovaVenda();
       initComponents();
       iniciarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVendaBotoes = new javax.swing.JPanel();
        jbVendaSalvar = new javax.swing.JButton();
        jbVendaConferirEstoque = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jpVendaFormulario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfVendaProdutoId = new javax.swing.JTextField();
        jtfVendaProdutoDescricao = new javax.swing.JTextField();
        jbPesquisaProduto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtfVendaIdCliente = new javax.swing.JTextField();
        jbPesquisaCliente = new javax.swing.JButton();
        jtfVendaClienteNome = new javax.swing.JTextField();
        jlVendaRazaoSocial = new javax.swing.JLabel();
        jtfVendaRazaoSocial = new javax.swing.JTextField();
        jtfVendaNomeFantasia = new javax.swing.JTextField();
        jlVendaNomeFantasia = new javax.swing.JLabel();
        jtfVendaCnpj = new javax.swing.JTextField();
        jlVendaCnpj = new javax.swing.JLabel();
        jlVendaTipoEmbalagem = new javax.swing.JLabel();
        jtfVendaTipoEmbalagem = new javax.swing.JTextField();
        jtfVendaEstoqueAtual = new javax.swing.JTextField();
        jlVendaEstoqueAtual = new javax.swing.JLabel();
        jtfVendaQuantidade = new javax.swing.JTextField();
        jlVendaQuantidade = new javax.swing.JLabel();
        jbVendaEditarProduto = new javax.swing.JButton();
        jbVendaRemoverProduto = new javax.swing.JButton();
        jlNomeCliente = new javax.swing.JLabel();
        jlDescricaoProduto = new javax.swing.JLabel();
        jbVendaAddProduto = new javax.swing.JButton();
        jpTabelaProdutosInseridos = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Lançamento de Venda");
        setPreferredSize(new java.awt.Dimension(730, 600));

        jbVendaSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        jbVendaSalvar.setText("Salvar");

        jbVendaConferirEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conferir.png"))); // NOI18N
        jbVendaConferirEstoque.setText("Conferir Estoque Atual");
        jbVendaConferirEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVendaConferirEstoqueActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalizar.png"))); // NOI18N
        jButton1.setText("Finalizar");

        javax.swing.GroupLayout jpVendaBotoesLayout = new javax.swing.GroupLayout(jpVendaBotoes);
        jpVendaBotoes.setLayout(jpVendaBotoesLayout);
        jpVendaBotoesLayout.setHorizontalGroup(
            jpVendaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendaBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbVendaSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbVendaConferirEstoque)
                .addContainerGap())
        );
        jpVendaBotoesLayout.setVerticalGroup(
            jpVendaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendaBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVendaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVendaSalvar)
                    .addComponent(jbVendaConferirEstoque)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Produto");

        jtfVendaProdutoId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfVendaProdutoIdFocusLost(evt);
            }
        });

        jtfVendaProdutoDescricao.setEnabled(false);

        jbPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisa-16.png"))); // NOI18N
        jbPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente");

        jtfVendaIdCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfVendaIdClienteFocusLost(evt);
            }
        });
        jtfVendaIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVendaIdClienteActionPerformed(evt);
            }
        });

        jbPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisa-16.png"))); // NOI18N
        jbPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaClienteActionPerformed(evt);
            }
        });

        jtfVendaClienteNome.setEnabled(false);

        jlVendaRazaoSocial.setText("Razão Social");

        jtfVendaRazaoSocial.setEnabled(false);
        jtfVendaRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVendaRazaoSocialActionPerformed(evt);
            }
        });

        jtfVendaNomeFantasia.setEnabled(false);
        jtfVendaNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVendaNomeFantasiaActionPerformed(evt);
            }
        });

        jlVendaNomeFantasia.setText("Nome Fantasia");

        jtfVendaCnpj.setEnabled(false);
        jtfVendaCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVendaCnpjActionPerformed(evt);
            }
        });

        jlVendaCnpj.setText("CNPJ");

        jlVendaTipoEmbalagem.setText("Tipo Embalagem");

        jtfVendaTipoEmbalagem.setEnabled(false);
        jtfVendaTipoEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVendaTipoEmbalagemActionPerformed(evt);
            }
        });

        jtfVendaEstoqueAtual.setEnabled(false);
        jtfVendaEstoqueAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVendaEstoqueAtualActionPerformed(evt);
            }
        });

        jlVendaEstoqueAtual.setText("Estoque Atual");

        jtfVendaQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVendaQuantidadeActionPerformed(evt);
            }
        });

        jlVendaQuantidade.setText("Quantidade");

        jbVendaEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar-16.png"))); // NOI18N
        jbVendaEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVendaEditarProdutoActionPerformed(evt);
            }
        });

        jbVendaRemoverProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remove-16.png"))); // NOI18N
        jbVendaRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVendaRemoverProdutoActionPerformed(evt);
            }
        });

        jlNomeCliente.setText("Nome");

        jlDescricaoProduto.setText("Descrição");

        jbVendaAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adicionarabaixo-16.png"))); // NOI18N
        jbVendaAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVendaAddProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpVendaFormularioLayout = new javax.swing.GroupLayout(jpVendaFormulario);
        jpVendaFormulario.setLayout(jpVendaFormularioLayout);
        jpVendaFormularioLayout.setHorizontalGroup(
            jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlVendaCnpj)
                    .addComponent(jtfVendaCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfVendaNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlVendaNomeFantasia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlVendaRazaoSocial)
                            .addComponent(jtfVendaRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                        .addComponent(jlVendaTipoEmbalagem)
                        .addGap(31, 31, 31)
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlVendaEstoqueAtual)
                            .addComponent(jtfVendaEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlVendaQuantidade)
                            .addComponent(jtfVendaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addComponent(jbVendaAddProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jbVendaEditarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbVendaRemoverProduto))
                    .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                                .addComponent(jtfVendaIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jbPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                                .addComponent(jlNomeCliente)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfVendaClienteNome)))
                    .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfVendaTipoEmbalagem, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpVendaFormularioLayout.createSequentialGroup()
                                    .addComponent(jtfVendaProdutoId, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(jbPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                                .addComponent(jlDescricaoProduto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfVendaProdutoDescricao))))
                .addContainerGap())
        );
        jpVendaFormularioLayout.setVerticalGroup(
            jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jlNomeCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfVendaIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfVendaClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfVendaNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfVendaRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlVendaNomeFantasia)
                            .addComponent(jlVendaRazaoSocial))
                        .addGap(32, 32, 32)))
                .addComponent(jlVendaCnpj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfVendaCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlDescricaoProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfVendaProdutoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfVendaProdutoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbPesquisaProduto))
                        .addGap(16, 16, 16)
                        .addComponent(jlVendaTipoEmbalagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfVendaTipoEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpVendaFormularioLayout.createSequentialGroup()
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlVendaEstoqueAtual)
                            .addComponent(jlVendaQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpVendaFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfVendaEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfVendaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbVendaEditarProduto)
                    .addComponent(jbVendaRemoverProduto)
                    .addComponent(jbVendaAddProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpTabelaProdutosInseridosLayout = new javax.swing.GroupLayout(jpTabelaProdutosInseridos);
        jpTabelaProdutosInseridos.setLayout(jpTabelaProdutosInseridosLayout);
        jpTabelaProdutosInseridosLayout.setHorizontalGroup(
            jpTabelaProdutosInseridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpTabelaProdutosInseridosLayout.setVerticalGroup(
            jpTabelaProdutosInseridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpVendaBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpVendaFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTabelaProdutosInseridos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpVendaBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpVendaFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTabelaProdutosInseridos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarTabela(){
        gerarTabela.limparTabela();
        
        Map<ProdutoModel, Integer> produtosSelecionados = (LinkedHashMap) vendaController.getVendaAtual().getProdutosSelecionados();
        
        produtosSelecionados.forEach((produto,quantidade) -> {
            gerarTabela.addLinha(new String[]{
                produto.getId().toString(), 
                produto.getDescricao(), 
                quantidade.toString(),
                produto.getUnidade(),
                produto.getPreco().multiply(new BigDecimal(quantidade)).toString(),
                produto.getEstoque().toString()});
        });
        
        jpTabelaProdutosInseridos.setLayout(new BorderLayout());
        jpTabelaProdutosInseridos.add(gerarTabela.getScrollPane(), BorderLayout.CENTER);
        jpTabelaProdutosInseridos.setVisible(true);
        jpTabelaProdutosInseridos.revalidate();
        jpTabelaProdutosInseridos.repaint();
    }
    
    private void jtfVendaIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVendaIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVendaIdClienteActionPerformed

    private void jtfVendaRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVendaRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVendaRazaoSocialActionPerformed

    private void jtfVendaNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVendaNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVendaNomeFantasiaActionPerformed

    private void jtfVendaCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVendaCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVendaCnpjActionPerformed

    private void jbPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaProdutoActionPerformed
        ConsultaProdutosView consultaProduto = new ConsultaProdutosView(this);
        ExibirJanelaUtil.abrirFormulario(consultaProduto, super.getDesktopPane());
    }//GEN-LAST:event_jbPesquisaProdutoActionPerformed

    private void jtfVendaTipoEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVendaTipoEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVendaTipoEmbalagemActionPerformed

    private void jtfVendaEstoqueAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVendaEstoqueAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVendaEstoqueAtualActionPerformed

    private void jtfVendaQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVendaQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVendaQuantidadeActionPerformed

    private void jbVendaEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVendaEditarProdutoActionPerformed
        System.out.println(gerarTabela.dadosLinhaSelecionada());
    }//GEN-LAST:event_jbVendaEditarProdutoActionPerformed

    private void jbVendaRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVendaRemoverProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVendaRemoverProdutoActionPerformed

    private void jtfVendaIdClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfVendaIdClienteFocusLost
        if(!jtfVendaIdCliente.getText().isEmpty()){
            try{
                Integer id = Integer.parseInt(jtfVendaIdCliente.getText());
                populaCamposCliente(clienteController.getClienteById(id));
            }
            catch(SQLException | NullPointerException eSql){
                JOptionPane.showMessageDialog(null, "Cliente não encontrado", "Erro", JOptionPane.WARNING_MESSAGE);
                limpaCamposCliente();
            }
            catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Você deve digitar um numero", "Erro", JOptionPane.ERROR_MESSAGE);
                 limpaCamposCliente();
            }
        }
    }//GEN-LAST:event_jtfVendaIdClienteFocusLost

    private void jbPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaClienteActionPerformed
        ConsultaClienteView consultaCliente = new ConsultaClienteView(this);
        ExibirJanelaUtil.abrirFormulario(consultaCliente, super.getDesktopPane());
    }//GEN-LAST:event_jbPesquisaClienteActionPerformed

    private void jbVendaAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVendaAddProdutoActionPerformed
        if(!jtfVendaProdutoId.getText().isEmpty()){
            try {
                Integer quantidade = Integer.parseInt(jtfVendaQuantidade.getText());
                vendaController.getVendaAtual().adicionarProduto(produtoController.getProdutoById(Integer.parseInt(jtfVendaProdutoId.getText())), quantidade);
                limpaCamposProduto();
                jtfVendaQuantidade.setText("");
                iniciarTabela();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Produto não encontrado", "Erro", JOptionPane.WARNING_MESSAGE);
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro ao inserir produto na venda", "Erro", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jbVendaAddProdutoActionPerformed

    private void jtfVendaProdutoIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfVendaProdutoIdFocusLost
        if(!jtfVendaProdutoId.getText().isEmpty()){
            try{
                Integer id = Integer.parseInt(jtfVendaProdutoId.getText());
                popularCamposProduto(produtoController.getProdutoById(id));
            }
            catch(SQLException | NullPointerException eSql){
                JOptionPane.showMessageDialog(null, "Produto não encontrado", "Erro", JOptionPane.WARNING_MESSAGE);
                limpaCamposProduto();
            }
            catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Você deve digitar um numero", "Erro", JOptionPane.ERROR_MESSAGE);
                 limpaCamposProduto();
            }
        }
    }//GEN-LAST:event_jtfVendaProdutoIdFocusLost

    private void jbVendaConferirEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVendaConferirEstoqueActionPerformed
        try {
            produtoController.sincronizarProdutosApiBdLocal();
            vendaController.atualizaEstoqueProdutosVendaAtual();
            iniciarTabela();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao sincronizar estoque atual", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbVendaConferirEstoqueActionPerformed
    
    protected void populaCamposCliente(ClienteModel cliente){
        jtfVendaIdCliente.setText(cliente.getId().toString());
        jtfVendaClienteNome.setText(cliente.getNome());
        jtfVendaNomeFantasia.setText(cliente.getNomeFantasia());
        jtfVendaRazaoSocial.setText(cliente.getRazaoSocial());
        jtfVendaCnpj.setText(cliente.getCnpj());
    }
    
    protected void populaCamposCliente(Integer id){
        ClienteModel cliente;
        try {
            cliente = clienteController.getClienteById(id);
            jtfVendaIdCliente.setText(cliente.getId().toString());
            jtfVendaClienteNome.setText(cliente.getNome());
            jtfVendaNomeFantasia.setText(cliente.getNomeFantasia());
            jtfVendaRazaoSocial.setText(cliente.getRazaoSocial());
            jtfVendaCnpj.setText(cliente.getCnpj());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado", "Erro", JOptionPane.WARNING_MESSAGE);
            limpaCamposCliente();
        }
    }
    
    private void limpaCamposCliente(){
        jtfVendaIdCliente.setText("");
        jtfVendaClienteNome.setText("");
        jtfVendaNomeFantasia.setText("");
        jtfVendaRazaoSocial.setText("");
        jtfVendaCnpj.setText("");
    }
    
    protected void popularCamposProduto(ProdutoModel produto){
        jtfVendaProdutoId.setText(produto.getId().toString());
        jtfVendaProdutoDescricao.setText(produto.getDescricao());
        jtfVendaTipoEmbalagem.setText(produto.getUnidade());
        jtfVendaEstoqueAtual.setText(produto.getEstoque().toString());
    }
    
    protected void popularCamposProduto(Integer id){
        ProdutoModel produto;
        try{
            produto = produtoController.getProdutoById(id);
            jtfVendaProdutoId.setText(produto.getId().toString());
            jtfVendaProdutoDescricao.setText(produto.getDescricao());
            jtfVendaTipoEmbalagem.setText(produto.getUnidade());
            jtfVendaEstoqueAtual.setText(produto.getEstoque().toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Produto não encontrado", "Erro", JOptionPane.WARNING_MESSAGE);
            limpaCamposCliente();
        }
        
    }
    
    private void limpaCamposProduto(){
        jtfVendaProdutoId.setText("");
        jtfVendaProdutoDescricao.setText("");
        jtfVendaTipoEmbalagem.setText("");
        jtfVendaEstoqueAtual.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbPesquisaCliente;
    private javax.swing.JButton jbPesquisaProduto;
    private javax.swing.JButton jbVendaAddProduto;
    private javax.swing.JButton jbVendaConferirEstoque;
    private javax.swing.JButton jbVendaEditarProduto;
    private javax.swing.JButton jbVendaRemoverProduto;
    private javax.swing.JButton jbVendaSalvar;
    private javax.swing.JLabel jlDescricaoProduto;
    private javax.swing.JLabel jlNomeCliente;
    private javax.swing.JLabel jlVendaCnpj;
    private javax.swing.JLabel jlVendaEstoqueAtual;
    private javax.swing.JLabel jlVendaNomeFantasia;
    private javax.swing.JLabel jlVendaQuantidade;
    private javax.swing.JLabel jlVendaRazaoSocial;
    private javax.swing.JLabel jlVendaTipoEmbalagem;
    private javax.swing.JPanel jpTabelaProdutosInseridos;
    private javax.swing.JPanel jpVendaBotoes;
    private javax.swing.JPanel jpVendaFormulario;
    private javax.swing.JTextField jtfVendaClienteNome;
    private javax.swing.JTextField jtfVendaCnpj;
    private javax.swing.JTextField jtfVendaEstoqueAtual;
    private javax.swing.JTextField jtfVendaIdCliente;
    private javax.swing.JTextField jtfVendaNomeFantasia;
    private javax.swing.JTextField jtfVendaProdutoDescricao;
    private javax.swing.JTextField jtfVendaProdutoId;
    private javax.swing.JTextField jtfVendaQuantidade;
    private javax.swing.JTextField jtfVendaRazaoSocial;
    private javax.swing.JTextField jtfVendaTipoEmbalagem;
    // End of variables declaration//GEN-END:variables
}
